---
title: "Linear Models"
author: "Jon Brock"
date: "11/11/2019"
output: github_document
---

```{r}
library(tidyverse)
library(p8105.datasets)

set.seed(1)
```

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    boro = neighbourhood_group,
    neighborhood = neighbourhood) %>% 
  filter(boro != "Staten Island") %>% 
  select(price, stars, boro, neighborhood, room_type)
```

## Fit a linear model

```{r}
fit <- lm(price ~ stars + boro, data = nyc_airbnb)
```

```{r}
fit

summary(fit)
coef(fit)
summary(fit)$coef
```

## Tidy the results
```{r}
fit %>% 
    broom::tidy() %>% 
    mutate(term = str_replace(term, "boro", "Boro: ")) %>% 
    knitr::kable(digits = 3)
```


## Take a look at factors
```{r}
nyc_airbnb <- 
    nyc_airbnb %>% 
    mutate(
        boro = fct_infreq(boro), # fct_infreq will reorder factors according to frequency
        room_type = fct_infreq(room_type))
```

## Refit the last model
```{r}
fit <- lm(price ~ stars + boro, data = nyc_airbnb)

fit %>% 
    broom::tidy() # more useful function of broom

fit %>%
    broom::glance() # good to know that this broom function exists
                    # the p-value in this output corresponds to the F statistic
```

## Diagnostics - Mostly checking residuals
### 'modelr' package

```{r}
modelr::add_residuals(nyc_airbnb, fit) %>% 
    ggplot(aes(x = boro, y = resid)) +
    geom_violin() +
    ylim(-500, 500)

modelr::add_residuals(nyc_airbnb, fit) %>% 
    ggplot(aes(x = stars, y = resid)) +
    geom_point() +
    ylim(-500, 500)

modelr::add_predictions(nyc_airbnb, fit) # adds predicted values
```

## Nesting data

```{r}
# fitting an interaction model
fit_interaction <- lm(price ~ stars * boro, data = nyc_airbnb)

fit_interaction %>% 
    broom::tidy()

########

fit_interaction <- lm(price ~ stars * boro + room_type * boro, data = nyc_airbnb)

fit_interaction %>% 
    broom::tidy()
```

```{r}
nyc_airbnb %>% 
    filter(boro == "Brooklyn") %>% 
    lm(price ~ stars + room_type, data = .) %>% 
    broom::tidy()
```

## Purrr and Mapping

```{r}
# applying our linear model to each boro iteratively
nyc_airbnb %>% 
    nest(data = -boro) %>% 
    mutate(
        models = map(.x = data, ~lm(price ~ stars + room_type, data = .x)),
        results = map(models, broom::tidy)) %>% 
    select(boro, results) %>% 
    unnest(results)
```

```{r}
# nesting by neighborhood (???)
nyc_airbnb %>% 
    filter(boro == "Manhattan") %>% 
    nest(data = -neighborhood) %>% 
    mutate(
        models = map(.x = data, ~lm(price ~ stars + room_type, data = .x)),
        results = map(models, broom::tidy)) %>% 
    select(neighborhood, results) %>% 
    unnest(results)
```

```{r}
manhattan_nest_lm_results <-
    nyc_airbnb %>% 
    filter(boro == "Manhattan") %>% 
    nest(data = -neighborhood) %>% 
    mutate(
        models = map(.x = data, ~lm(price ~ stars + room_type, data = .x)),
        results = map(models, broom::tidy)) %>% 
    select(neighborhood, results) %>% 
    unnest(results)

manhattan_nest_lm_results %>% 
  filter(str_detect(term, "room_type")) %>% 
  ggplot(aes(x = neighborhood, y = estimate)) + 
  geom_point() + 
  facet_wrap(~term) + 
  theme(axis.text.x = element_text(angle = 80, hjust = 1))
```

```{r}
nyc_airbnb %>% 
    filter(neighborhood == "NoHo", room_type == "Shared room")
```

## Logistic regression model

```{r}
# Note: this code will not work because of a lack of import of the dataset
# Use for illustrative purposes

fit_logistic <-
    baltimore_df %>% 
    glm(resolved ~ victim_age + victim_race + victim_sex, data = ., family = binomial())

fit_logistic <-
    broom::tidy() %>% 
    mutate(OR = exp(estimate)) %>% 
    select(term, log_OR = estimate, OR, p.value) %>% 
    knitr::kable(digits = 3)
```

